# Generated by Django 5.2.8 on 2025-11-26 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='carousel/')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Título/Descripción')),
                ('order', models.IntegerField(default=0, verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Imagen del Carrusel',
                'verbose_name_plural': 'Imágenes del Carrusel',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CustomCareImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='custom_care/')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Imagen Cuidado Personalizado',
                'verbose_name_plural': 'Imagen Cuidado Personalizado',
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='unique_active_custom_care_image_constraint')],
            },
        ),
    ]
