# Generated by Django 5.2.8 on 2025-11-26 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CasaReposo', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomCareImage',
        ),
    ]
