# Generated by Django 5.2.8 on 2025-11-26 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CasaReposo', '0002_delete_customcareimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carouselimage',
            options={'verbose_name': 'Imagen del Carrusel', 'verbose_name_plural': 'Imágenes del Carrusel'},
        ),
    ]
