# Generated by Django 5.2.8 on 2025-11-26 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CasaReposo', '0003_alter_carouselimage_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Título de la Foto')),
                ('image', models.ImageField(upload_to='gallery/general/', verbose_name='Archivo de Imagen')),
                ('category', models.CharField(choices=[('PATIO', 'Patio/Jardín'), ('COMUN', 'Área Común/Salón'), ('FACHADA', 'Fachada/Exterior'), ('OTRO', 'Otro')], default='COMUN', max_length=50, verbose_name='Categoría')),
                ('is_active', models.BooleanField(default=True, verbose_name='Mostrar en Galería')),
                ('order', models.IntegerField(default=0, verbose_name='Orden de visualización')),
            ],
            options={
                'verbose_name': 'Foto de Galería (General)',
                'verbose_name_plural': 'Fotos de Galería (General)',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la Habitación')),
                ('main_image', models.ImageField(upload_to='gallery/rooms/', verbose_name='Foto Principal')),
                ('description', models.TextField(help_text='Descripción detallada de la habitación.', verbose_name='Descripción')),
                ('details', models.TextField(help_text='Lista de detalles o servicios incluidos. Usa saltos de línea para listar.', verbose_name='Detalles/Incluye')),
                ('price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Precio base mensual (opcional)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Mostrar en Galería')),
                ('order', models.IntegerField(default=0, verbose_name='Orden de visualización')),
            ],
            options={
                'verbose_name': 'Tipo de Habitación',
                'verbose_name_plural': 'Tipos de Habitaciones',
                'ordering': ['order'],
            },
        ),
        migrations.AlterModelOptions(
            name='carouselimage',
            options={'ordering': ['order'], 'verbose_name': 'Imagen del Carrusel', 'verbose_name_plural': 'Imágenes del Carrusel'},
        ),
    ]
