# Generated by Django 5.2.8 on 2025-11-26 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CasaReposo', '0004_galleryphoto_roomtype_alter_carouselimage_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncludedService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Servicio Incluido')),
                ('description', models.TextField(blank=True, help_text='Detalle breve del servicio.', verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Mostrar en lista')),
                ('order', models.IntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Servicio Incluido',
                'verbose_name_plural': 'Servicios Incluidos',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='OptionalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Servicio Opcional')),
                ('cost', models.CharField(help_text="Ej: '$15.000', 'Según requerimiento', 'Consultar'.", max_length=100, verbose_name='Costo/Frecuencia')),
                ('is_active', models.BooleanField(default=True, verbose_name='Mostrar en lista')),
                ('order', models.IntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Servicio Opcional',
                'verbose_name_plural': 'Costos de Servicios Opcionales',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='RateCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_type', models.CharField(max_length=150, verbose_name='Tipo de Paciente/Estadía')),
                ('weekly_rate', models.DecimalField(blank=True, decimal_places=0, help_text='Monto sin puntos ni comas. Dejar en blanco si no aplica.', max_digits=10, null=True, verbose_name='Tarifa Semanal (CLP)')),
                ('monthly_rate', models.DecimalField(decimal_places=0, help_text='Monto sin puntos ni comas.', max_digits=10, verbose_name='Tarifa Mensual (CLP)')),
                ('notes', models.CharField(blank=True, help_text="Ej: 'Solo estadías cortas', 'Sujeto a evaluación médica'.", max_length=255, verbose_name='Nota Adicional')),
                ('is_active', models.BooleanField(default=True, verbose_name='Mostrar en tabla')),
                ('order', models.IntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Categoría de Tarifa',
                'verbose_name_plural': 'Tarifas de Estadía',
                'ordering': ['order'],
            },
        ),
    ]
