# Generated by Django 5.2.8 on 2025-11-30 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CasaReposo', '0005_includedservice_optionalservice_ratecategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('mensaje', models.TextField()),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('respondido', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Mensaje de Contacto',
                'verbose_name_plural': 'Mensajes de Contacto',
                'ordering': ['-fecha_envio'],
            },
        ),
    ]
