# Generated by Django 6.0 on 2025-12-10 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CasaReposo', '0006_contactmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carouselimage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='galleryphoto',
            name='image',
        ),
        migrations.RemoveField(
            model_name='roomtype',
            name='main_image',
        ),
        migrations.AddField(
            model_name='carouselimage',
            name='image_url',
            field=models.CharField(default='', help_text='Pega aquí el enlace de Imgur/Google Fotos. Máx 500 caracteres.', max_length=500, verbose_name='URL de Imagen Pública'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='galleryphoto',
            name='image_url',
            field=models.CharField(default='', help_text='Pega aquí el enlace de la imagen de galería. Máx 500 caracteres.', max_length=500, verbose_name='URL de Archivo de Imagen'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roomtype',
            name='main_image_url',
            field=models.CharField(default='', help_text='Pega aquí el enlace de la imagen principal. Máx 500 caracteres.', max_length=500, verbose_name='URL de Foto Principal'),
            preserve_default=False,
        ),
    ]
